### ISSUE TITLE
Error in Range to CIDR support 

### ISSUE THREAD

**Issue by Zer0-Tolerance** [vrurg/perl6-IP-Addr#7]
Hi, 
Thanks for this module, Im trying to convert IP range to CIDR but it seems the module is not behaving correctly:
```
[1] > say IP::Addr.new( "192.1.1.3/24" ).network;
192.1.1.0/24
[1] > say IP::Addr.new( "192.168.1.1-192.168.1.255" ).network;
192.1.1.1/0
```
I've tried with any ranges the prefix is always /0 , can you have a look to fix it ?

**Comment by vrurg** [comment]
Actually, this is not a bug. The module wasn't designed as an IP calculator. Correspondingly, an address range is not supposed to have a mask. I'd say, `network` method is rather to return a `Failure` if invoked on a range.

The functionality you're looking for worth a dedicated `IP::Addr::Calc` module, perhaps.
